### ISSUE TITLE
I am getting an error in index.js involving the setInterval() line.

### ISSUE THREAD

**Issue by WarhawkYT** [ParadoxalCorp/FelixBot#173]
On like 45 in index.js I am getting an error every time I run the bot. It says 
/home/ec2-user/environment/index.js:45
        setInterval(async() => {
                                  ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

I am running it on aws just to let  you know.

**Comment by ParadoxOrigins** [comment]
What version of nodejs are you using
